package com.nibss.nfp.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NIPInterface", targetNamespace = "http://core.nip.nibss/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NIPInterface {


    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "accountunblock", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.Accountunblock")
    @ResponseWrapper(localName = "accountunblockResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.AccountunblockResponse")
    public String accountunblock(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "balanceenquiry", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.Balanceenquiry")
    @ResponseWrapper(localName = "balanceenquiryResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.BalanceenquiryResponse")
    public String balanceenquiry(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "fundtransferAdvice_dd")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fundtransferAdvice_dd", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.FundtransferAdviceDd")
    @ResponseWrapper(localName = "fundtransferAdvice_ddResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.FundtransferAdviceDdResponse")
    public String fundtransferAdviceDd(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "mandateadvice", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.Mandateadvice")
    @ResponseWrapper(localName = "mandateadviceResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.MandateadviceResponse")
    public String mandateadvice(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "fundtransferAdvice_dc")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fundtransferAdvice_dc", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.FundtransferAdviceDc")
    @ResponseWrapper(localName = "fundtransferAdvice_dcResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.FundtransferAdviceDcResponse")
    public String fundtransferAdviceDc(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "fundtransfersingleitem_dc")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fundtransfersingleitem_dc", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.FundtransfersingleitemDc")
    @ResponseWrapper(localName = "fundtransfersingleitem_dcResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.FundtransfersingleitemDcResponse")
    public String fundtransfersingleitemDc(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "accountblock", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.Accountblock")
    @ResponseWrapper(localName = "accountblockResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.AccountblockResponse")
    public String accountblock(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "fundtransfersingleitem_dd")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fundtransfersingleitem_dd", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.FundtransfersingleitemDd")
    @ResponseWrapper(localName = "fundtransfersingleitem_ddResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.FundtransfersingleitemDdResponse")
    public String fundtransfersingleitemDd(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "amountblock", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.Amountblock")
    @ResponseWrapper(localName = "amountblockResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.AmountblockResponse")
    public String amountblock(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nameenquirysingleitem", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.Nameenquirysingleitem")
    @ResponseWrapper(localName = "nameenquirysingleitemResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.NameenquirysingleitemResponse")
    public String nameenquirysingleitem(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "amountunblock", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.Amountunblock")
    @ResponseWrapper(localName = "amountunblockResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.AmountunblockResponse")
    public String amountunblock(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "financialinstitutionlist", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.Financialinstitutionlist")
    @ResponseWrapper(localName = "financialinstitutionlistResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.FinancialinstitutionlistResponse")
    public String financialinstitutionlist(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "txnstatusquerysingleitem", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.Txnstatusquerysingleitem")
    @ResponseWrapper(localName = "txnstatusquerysingleitemResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.TxnstatusquerysingleitemResponse")
    public String txnstatusquerysingleitem(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "adjustNIPSettings", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.AdjustNIPSettings")
    @ResponseWrapper(localName = "adjustNIPSettingsResponse", targetNamespace = "http://core.nip.nibss/", className = "com.nibss.service_shell.nip.webservice.AdjustNIPSettingsResponse")
    public String adjustNIPSettings(
        @WebParam(name = "request", targetNamespace = "")
        String request);

}
